### ISSUE TITLE
B1B and H6J can not control the flaps and gears

### ISSUE THREAD

**Issue by DF110071** [necr0n/dcs-make-flyable#15]
how can I fix it?

**Comment by DF110071** [comment]
And B52H's engine smoke are only appeared on the left,can anyway fixed it?

**Comment by necr0n** [comment]
At least gears and flaps are broken for all mods with the Su-25 base with the release of FC24 two weeks ago, likely due to new Default Assignments/Wizard keys

Tried a few things, nothing's worked so far - iCommandPlaneGear is called but nothing happens. 

Haven't seen a fix that doesn't break IC/introduces a separate FM - please let ED know on ED Forums.

**Comment by DF110071** [comment]
> At least gears and flaps are broken for all mods with the Su-25 base with the release of FC24 two weeks ago, likely due to new Default Assignments/Wizard keys
> 
> Tried a few things, nothing's worked so far - iCommandPlaneGear is called but nothing happens.
> 
> Haven't seen a fix that doesn't break IC/introduces a separate FM - please let ED know on ED Forums.

okey thx so much ：）
